# === Dev overrides ===
quarkus.log.console.json=false
quarkus.hibernate-orm.log.sql=true
quarkus.swagger-ui.always-include=true

# Banco local (docker-compose)
quarkus.datasource.username=fht_user
quarkus.datasource.password=fht_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://127.0.0.1:5433/fht_db
